import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ExternalLink, Grid2X2, Loader2, Plus, ShieldCheck, Trash2, Users } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";

const formatDate = (date: Date | string | null | undefined) => date ? new Date(date).toLocaleDateString("de-DE", { day: "2-digit", month: "short", year: "numeric" }) : "—";

export default function Admin() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const isAdmin = user?.role === "admin";
  const appsQuery = trpc.apps.adminList.useQuery(undefined, { enabled: isAdmin });
  const usersQuery = trpc.admin.users.useQuery(undefined, { enabled: isAdmin });
  const createMutation = trpc.apps.create.useMutation({ onSuccess: async () => { await utils.apps.adminList.invalidate(); await utils.apps.list.invalidate(); toast.success("App wurde hinzugefügt."); setForm({ name: "", url: "", description: "", category: "custom" }); }, onError: error => toast.error(error.message || "App konnte nicht angelegt werden.") });
  const archiveMutation = trpc.apps.archive.useMutation({ onSuccess: async () => { await utils.apps.adminList.invalidate(); await utils.apps.list.invalidate(); toast.success("App wurde deaktiviert."); }, onError: error => toast.error(error.message || "App konnte nicht deaktiviert werden.") });
  const [form, setForm] = useState({ name: "", url: "", description: "", category: "custom" });

  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.name || !form.url) return; createMutation.mutate(form); };
  if (!isAdmin) return <DashboardLayout><div className="mx-auto max-w-2xl rounded-[1.75rem] bg-white p-10 text-center shadow-sm"><ShieldCheck className="mx-auto h-10 w-10 text-[#b56b2d]" /><h1 className="mt-5 text-2xl font-semibold text-[#303631]">Keine Admin-Berechtigung</h1><p className="mt-3 text-sm leading-6 text-[#7f8781]">Dieser Bereich ist nur für das TBS-Administratorkonto freigeschaltet.</p><Link href="/" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#0f766e]"><ArrowLeft className="h-4 w-4" />Zur Übersicht</Link></div></DashboardLayout>;

  return <DashboardLayout><div className="mx-auto max-w-[1360px]"><header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#0f766e]">TBS / ADMINISTRATION</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-[#202321] sm:text-4xl">Workspace verwalten.</h1><p className="mt-3 text-sm leading-6 text-[#737b75]">Verwalte Links im Launchpad und behalte den Überblick über berechtigte Konten.</p></div><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#0f766e]"><ArrowLeft className="h-4 w-4" />Zur Übersicht</Link></header>

    <div className="mt-8 grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><Card className="rounded-[1.5rem] border-0 bg-[#202a28] text-white shadow-[0_18px_50px_rgba(31,41,39,0.14)]"><CardHeader className="p-6 pb-2"><div className="flex items-center justify-between"><CardTitle className="text-lg font-semibold">Neue App verknüpfen</CardTitle><div className="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><Plus className="h-5 w-5 text-[#a8e0d2]" /></div></div><p className="mt-2 text-sm leading-6 text-[#b8c8c3]">Füge eine Website hinzu, die im privaten Launchpad erscheinen soll.</p></CardHeader><CardContent className="p-6 pt-5"><form onSubmit={submit} className="space-y-4"><div><Label htmlFor="app-name" className="text-xs font-semibold text-[#d5e1dc]">Name</Label><Input id="app-name" value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="z. B. Projektmanagement" className="mt-2 border-white/15 bg-white/10 text-white placeholder:text-[#8ea39a] focus-visible:ring-[#8ed1be]" /></div><div><Label htmlFor="app-url" className="text-xs font-semibold text-[#d5e1dc]">URL</Label><Input id="app-url" type="url" value={form.url} onChange={event => setForm({ ...form, url: event.target.value })} placeholder="https://…" className="mt-2 border-white/15 bg-white/10 text-white placeholder:text-[#8ea39a] focus-visible:ring-[#8ed1be]" /></div><div><Label htmlFor="app-description" className="text-xs font-semibold text-[#d5e1dc]">Beschreibung <span className="font-normal text-[#8ea39a]">(optional)</span></Label><Input id="app-description" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Wofür nutzt du die App?" className="mt-2 border-white/15 bg-white/10 text-white placeholder:text-[#8ea39a] focus-visible:ring-[#8ed1be]" /></div><Button type="submit" disabled={createMutation.isPending || !form.name || !form.url} className="mt-2 h-11 w-full rounded-xl bg-[#a8e0d2] font-semibold text-[#173a35] hover:bg-[#c5eee4]">{createMutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />}App speichern</Button></form></CardContent></Card>

      <Card className="rounded-[1.5rem] border-0 bg-white shadow-sm"><CardHeader className="flex-row items-center justify-between p-6 pb-3"><div><CardTitle className="text-lg font-semibold text-[#303631]">Launchpad-Apps</CardTitle><p className="mt-1 text-sm text-[#7f8781]">Aktive und archivierte Verknüpfungen</p></div><Badge className="rounded-full border-0 bg-[#e1f1ed] text-[#0f766e]">{appsQuery.data?.length || 0} gesamt</Badge></CardHeader><CardContent className="p-6 pt-3">{appsQuery.isLoading ? <div className="flex justify-center py-12"><Loader2 className="h-5 w-5 animate-spin text-[#0f766e]" /></div> : <div className="divide-y divide-[#eeede8]">{appsQuery.data?.length ? appsQuery.data.map(app => <div key={app.id} className="flex items-center gap-4 py-4 first:pt-2"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e4ebf6] text-[#55729f]"><Grid2X2 className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#303631]">{app.name}</p><p className="truncate text-xs text-[#8a918b]">{app.url}</p></div><Badge variant="outline" className={app.isActive ? "border-[#b8ddd3] text-[#0f766e]" : "border-[#e3c5c0] text-[#a45a4a]"}>{app.isActive ? "Aktiv" : "Archiviert"}</Badge>{app.isActive ? <button title="App deaktivieren" onClick={() => archiveMutation.mutate({ id: app.id })} className="rounded-lg p-2 text-[#a3aaa5] transition-colors hover:bg-[#fff1ef] hover:text-[#b45343]"><Trash2 className="h-4 w-4" /></button> : <span className="w-8" />}</div>) : <div className="rounded-2xl bg-[#f7f6f1] p-8 text-center"><Grid2X2 className="mx-auto h-6 w-6 text-[#aab1ab]" /><p className="mt-3 text-sm font-medium text-[#58605a]">Noch keine eigenen Apps</p><p className="mt-1 text-xs text-[#929891]">Lege links deine erste Verknüpfung an.</p></div>}</div>}</CardContent></Card></div>

    <Card className="mt-6 rounded-[1.5rem] border-0 bg-white shadow-sm"><CardHeader className="flex-row items-center justify-between p-6 pb-3"><div><CardTitle className="flex items-center gap-2 text-lg font-semibold text-[#303631]"><Users className="h-5 w-5 text-[#0f766e]" />Nutzerkonten</CardTitle><p className="mt-1 text-sm text-[#7f8781]">Basisdaten für Zugriffsverwaltung und Überblick</p></div><Badge className="rounded-full border-0 bg-[#f2eee5] text-[#876a3e]">{usersQuery.data?.length || 0} Konten</Badge></CardHeader><CardContent className="overflow-x-auto p-6 pt-3">{usersQuery.isLoading ? <div className="flex justify-center py-12"><Loader2 className="h-5 w-5 animate-spin text-[#0f766e]" /></div> : <table className="w-full min-w-[640px] text-left"><thead><tr className="border-b border-[#eeede8] text-[10px] font-bold uppercase tracking-[0.16em] text-[#929891]"><th className="pb-3 pr-4">Konto</th><th className="pb-3 pr-4">Rolle</th><th className="pb-3 pr-4">Login</th><th className="pb-3">Zuletzt aktiv</th></tr></thead><tbody className="divide-y divide-[#f0efe9]">{usersQuery.data?.map(account => <tr key={account.id}><td className="py-4 pr-4"><p className="text-sm font-semibold text-[#303631]">{account.name || "Unbenannt"}</p><p className="mt-1 text-xs text-[#8a918b]">{account.email || "Keine E-Mail hinterlegt"}</p></td><td className="py-4 pr-4"><Badge variant="outline" className={account.role === "admin" ? "border-[#b8ddd3] text-[#0f766e]" : "border-[#deded6] text-[#7f8781]"}>{account.role === "admin" ? "Admin" : "Nutzer"}</Badge></td><td className="py-4 pr-4 text-sm text-[#69716b]">{account.loginMethod || "Manus"}</td><td className="py-4 text-sm text-[#69716b]">{formatDate(account.lastSignedIn)}</td></tr>)}</tbody></table>}</CardContent></Card>

    <div className="mt-6 flex items-start gap-3 rounded-2xl border border-[#d8e7e1] bg-[#eef7f4] p-4 text-sm leading-6 text-[#557068]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#0f766e]" /><p><strong className="font-semibold text-[#365d53]">Sicherheitsnotiz:</strong> TBS verwaltet keine Passwörter. E-Mail-Inhalte und Office-Dokumente bleiben bei den jeweiligen Diensten; hier werden nur Nutzer-Metadaten und deine App-Links angezeigt.</p></div>
  </div></DashboardLayout>;
}
