import { ArrowLeft, FileText, Image as ImageIcon, Mail, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { Link } from "wouter";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";

const icon = (type: string) => type === "mail" ? Mail : type === "photo" ? ImageIcon : FileText;

export default function Klaro() {
  const items = trpc.klaro.list.useQuery();
  return <DashboardLayout>
    <div className="mx-auto max-w-[1160px]">
      <header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#0f766e]">TBS / KLARO</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-[#202321] sm:text-4xl">Klaro, direkt im Workspace.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#737b75]">Sende ausgewählte TBS-Mails und Dateien in Klaro, damit daraus Fristen, Aufgaben und sichere Entwürfe entstehen können.</p></div><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#0f766e]"><ArrowLeft className="h-4 w-4" />Zur Übersicht</Link></header>
      <div className="mt-8 grid gap-5 md:grid-cols-3">{[{label:"Synchronisierte Elemente",value:items.data?.length ?? 0,desc:"Privat in deinem Konto"},{label:"Quellen",value:"Mail · Text · Fotos",desc:"Aus TBS ausgewählt"},{label:"Automatik",value:"Entwürfe",desc:"Keine externe Aktion ohne Bestätigung"}].map(item => <Card key={item.label} className="rounded-[1.35rem] border-0 bg-white shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#929891]">{item.label}</p><p className="mt-3 text-2xl font-semibold text-[#303631]">{item.value}</p><p className="mt-1 text-sm text-[#7f8781]">{item.desc}</p></CardContent></Card>)}</div>
      <Card className="mt-6 rounded-[1.5rem] border-0 bg-white shadow-sm"><CardHeader className="flex-row items-center justify-between p-6 pb-3"><div><CardTitle className="flex items-center gap-2 text-lg font-semibold text-[#303631]"><Sparkles className="h-5 w-5 text-[#0f766e]" />Klaro-Eingang</CardTitle><p className="mt-1 text-sm text-[#7f8781]">Diese Inhalte stehen Klaro für Analyse und Fristenmanagement zur Verfügung.</p></div><Button variant="outline" size="icon" onClick={() => items.refetch()} className="rounded-xl border-[#deded6]"><RefreshCw className="h-4 w-4" /></Button></CardHeader><CardContent className="p-6 pt-3">{items.isLoading ? <div className="py-12 text-center text-sm text-[#7f8781]">Synchronisation wird geladen …</div> : items.data?.length ? <div className="divide-y divide-[#eeede8]">{items.data.map(item => { const Icon = icon(item.sourceType); return <div key={item.id} className="flex items-start gap-4 py-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e1f1ed] text-[#0f766e]"><Icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#303631]">{item.title}</p><p className="mt-1 whitespace-pre-line text-sm leading-6 text-[#69716b]">{item.summary.slice(0, 320)}{item.summary.length > 320 ? " …" : ""}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[0.14em] text-[#a0a7a2]">{item.sourceType === "mail" ? "TBS-Mail" : item.sourceType === "photo" ? "TBS-Datei" : "TBS-Text"}</p></div></div> })}</div> : <div className="rounded-2xl border border-dashed border-[#cbd5cf] bg-[#fbfcfa] p-12 text-center"><Sparkles className="mx-auto h-7 w-7 text-[#0f766e]" /><h3 className="mt-4 text-base font-semibold text-[#303631]">Noch nichts synchronisiert</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#7f8781]">Öffne eine TBS-Mail, ein TBS-Textdokument oder ein Foto und wähle dort „An Klaro senden“.</p></div>}</CardContent></Card>
      <div className="mt-5 flex items-start gap-3 rounded-2xl border border-[#d8e7e1] bg-[#eef7f4] p-4 text-sm leading-6 text-[#557068]"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#0f766e]" /><p><strong className="font-semibold text-[#365d53]">Sicherheitsprinzip:</strong> Es werden nur ausdrücklich ausgewählte Inhalte synchronisiert. Klaro erstellt ausschließlich Vorschläge und Entwürfe. Keine Kündigung, Kontaktaufnahme oder andere externe Aktion wird automatisch ausgeführt.</p></div>
    </div>
  </DashboardLayout>;
}
