import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, BriefcaseBusiness, ExternalLink, Grid2X2, Mail, Plus, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const systemApps = [
  { name: "E-Mail", description: "Postfach und Kommunikation", href: "mailto:", icon: Mail, color: "bg-[#e1f1ed] text-[#0f766e]", note: "In deinem Mail-Client öffnen" },
  { name: "Office", description: "Dokumente und Zusammenarbeit", href: "https://www.office.com", icon: BriefcaseBusiness, color: "bg-[#f8e9d8] text-[#b56b2d]", note: "Microsoft Office online" },
];

export default function Workspace() {
  const { user } = useAuth();
  const { data: apps = [], isLoading: appsLoading } = trpc.apps.list.useQuery();
  const firstName = user?.name?.split(" ")[0] || "deinem";
  const customCount = apps.length;

  return <DashboardLayout><div className="mx-auto max-w-[1360px]">
    <header className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#0f766e]">TBS / WORKSPACE</p><h1 className="mt-3 text-3xl font-semibold tracking-[-0.04em] text-[#202321] sm:text-4xl">Willkommen in {firstName} Workspace.</h1><p className="mt-3 text-sm leading-6 text-[#737b75]">Dein persönlicher Startpunkt für Arbeit, Kommunikation und die Tools, die du täglich nutzt.</p></div><Badge className="w-fit rounded-full border-0 bg-[#e1f1ed] px-4 py-2 text-xs font-semibold text-[#0f766e]"><ShieldCheck className="mr-2 h-3.5 w-3.5" />Privat & geschützt</Badge></header>

    <section className="relative mt-8 overflow-hidden rounded-[1.75rem] bg-[#0f766e] p-7 text-white shadow-[0_20px_60px_rgba(15,118,110,0.18)] sm:p-9"><div className="absolute -right-12 -top-24 h-72 w-72 rounded-full border border-white/15" /><div className="absolute -bottom-32 right-32 h-64 w-64 rounded-full border border-white/10" /><div className="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#a8e0d2]">Quick launch</p><h2 className="mt-4 max-w-xl text-2xl font-semibold tracking-[-0.03em] sm:text-3xl">Direkt hinein in deinen Arbeitstag.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-[#c5e7df]">Öffne einen Bereich mit einem Klick. Deine Logins und Inhalte bleiben bei den jeweiligen Diensten.</p></div><div className="flex flex-wrap gap-3"><a href="mailto:" className="inline-flex h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-semibold text-[#0f766e] transition-transform hover:-translate-y-0.5 active:scale-[0.98]">E-Mail öffnen <ArrowUpRight className="h-4 w-4" /></a><a href="https://www.office.com" target="_blank" rel="noreferrer" className="inline-flex h-11 items-center gap-2 rounded-xl border border-white/25 bg-white/10 px-4 text-sm font-semibold text-white transition-colors hover:bg-white/15 active:scale-[0.98]">Office öffnen <ExternalLink className="h-4 w-4" /></a></div></div></section>

    <div className="mt-10 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#929891]">Launchpad</p><h2 className="mt-2 text-xl font-semibold tracking-[-0.03em] text-[#303631]">Deine Arbeitsbereiche</h2></div>{user?.role === "admin" && <Link href="/admin" className="hidden items-center gap-1.5 text-sm font-semibold text-[#0f766e] sm:flex">Apps verwalten <ArrowUpRight className="h-4 w-4" /></Link>}</div>
    <div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      {systemApps.map(app => <a key={app.name} href={app.href} target={app.href.startsWith("http") ? "_blank" : undefined} rel={app.href.startsWith("http") ? "noreferrer" : undefined} className="group"><Card className="h-full rounded-[1.35rem] border-0 bg-white shadow-[0_8px_30px_rgba(31,41,39,0.055)] transition-all duration-200 hover:-translate-y-1 hover:shadow-[0_16px_40px_rgba(31,41,39,0.1)]"><CardContent className="flex h-full min-h-[190px] flex-col p-6"><div className={`grid h-11 w-11 place-items-center rounded-2xl ${app.color}`}><app.icon className="h-5 w-5" /></div><div className="mt-auto flex items-end justify-between gap-3"><div><h3 className="text-base font-semibold text-[#303631]">{app.name}</h3><p className="mt-1 text-sm text-[#7f8781]">{app.description}</p></div><ArrowUpRight className="h-5 w-5 text-[#b0b7b2] transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-[#0f766e]" /></div><p className="mt-4 text-xs text-[#a0a7a2]">{app.note}</p></CardContent></Card></a>)}
      {appsLoading ? [1, 2].map(item => <div key={item} className="min-h-[190px] animate-pulse rounded-[1.35rem] bg-[#ecebe4]" />) : apps.map(app => <a key={app.id} href={app.url} target="_blank" rel="noreferrer" className="group"><Card className="h-full min-h-[190px] rounded-[1.35rem] border-0 bg-white shadow-[0_8px_30px_rgba(31,41,39,0.055)] transition-all duration-200 hover:-translate-y-1 hover:shadow-[0_16px_40px_rgba(31,41,39,0.1)]"><CardContent className="flex h-full flex-col p-6"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-[#e4ebf6] text-[#55729f]"><Grid2X2 className="h-5 w-5" /></div><ExternalLink className="h-4 w-4 text-[#b0b7b2] group-hover:text-[#0f766e]" /></div><div className="mt-auto"><h3 className="text-base font-semibold text-[#303631]">{app.name}</h3><p className="mt-1 line-clamp-2 text-sm text-[#7f8781]">{app.description || "Verknüpfte Anwendung"}</p><span className="mt-4 inline-block text-xs font-semibold uppercase tracking-[0.12em] text-[#0f766e]">{app.category}</span></div></CardContent></Card></a>)}
      <Link href="/admin" className="group"><Card className="h-full min-h-[190px] rounded-[1.35rem] border border-dashed border-[#cbd5cf] bg-transparent shadow-none transition-all hover:border-[#0f766e] hover:bg-white/50"><CardContent className="flex h-full flex-col items-center justify-center p-6 text-center"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white text-[#0f766e] shadow-sm"><Plus className="h-5 w-5" /></div><h3 className="mt-5 text-base font-semibold text-[#303631]">App hinzufügen</h3><p className="mt-1 max-w-[180px] text-sm leading-5 text-[#7f8781]">Verknüpfe eine weitere Website mit deinem Launchpad.</p></CardContent></Card></Link>
    </div>

    <section className="mt-10 grid gap-4 sm:grid-cols-3"><Card className="rounded-[1.25rem] border-0 bg-white shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#929891]">Launchpad</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em] text-[#303631]">{customCount + 2}</p><p className="mt-1 text-sm text-[#7f8781]">Arbeitsbereiche aktiv</p></CardContent></Card><Card className="rounded-[1.25rem] border-0 bg-white shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#929891]">Zugriff</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em] text-[#303631]">Privat</p><p className="mt-1 text-sm text-[#7f8781]">Nur angemeldete Konten</p></CardContent></Card><Card className="rounded-[1.25rem] border-0 bg-white shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#929891]">Datenhaltung</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em] text-[#303631]">Cloud-ready</p><p className="mt-1 text-sm text-[#7f8781]">App-Links und Nutzer getrennt</p></CardContent></Card></section>
  </div></DashboardLayout>;
}
